### ISSUE TITLE
Actividades no disponibles

### ISSUE THREAD

**Issue by profemacarena** [jamj2000/DAW2-DAW-Apuntes#1]
Es una pena que las actividades ya no carguen, eran muy interesantes.

**Comment by jamj2000** [comment]
Hola,
este curso no imparto clase de este Módulo y en el blog de Github.io se me ha desconfigurado y no se ven las actividades aunque siguen ahí.

En cuanto tenga un poquitín de tiempo, las haré disponibles en este repositorio.

**Comment by jamj2000** [comment]
Enunciados de las actividades ya disponibles.

**Comment by profemacarena** [comment]
Muchas gracias, es un material muy bueno que me dió mucha pena no volver a
acceder.
